// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqmerbdmexgxvaqyixmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbWVyYmRtZXhneHZhcXlpeG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMDQ1MjIsImV4cCI6MjA1Njg4MDUyMn0.yG48gp5K1tsQPn1fpuOud_ZHqAeBaz5aoXqn5o70UCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);